### ISSUE TITLE
Better error handling of crd deployments

### ISSUE THREAD

**Issue by s1113950** [IntelAI/mlt#319]
I was making changes to `--interactive` mode and noticed that 1 of my pods didn't deploy.
I ran this: `kubectl describe pytorchjobs.kubeflow.org -n robertso` and discovered this:
```
Status:
  Phase:             Creating
  Reason:            Could not create job resources; [Creating pod  returned error., Pod "py-dist-7d448722-b260-4f77-93bd-90972c40-master-4i9g-0-niwsz" is invalid: spec.containers[1].name: Duplicate value: "pytorch"]
  Replica Statuses:  <nil>
  State:             Running
```
but when I ran `mlt status` all I saw was this:
```
robertso@sylviasr-mobl1:/tmp/py-dist$ mlt status
PyTorch Job:
NAME                                           AGE
py-dist-7d448722-b260-4f77-93bd-90972c40a136   6m

Pods:
No resources found.
```
And `mlt logs` just showed this:
```
robertso@sylviasr-mobl1:/tmp/py-dist$ mlt logs
Checking for pod(s) readiness
Retrying 2/120
``` 
where it `retried` forever

To repro this, I added this in the `pytorch-distributed` job yaml by mistake:

```
template:
        spec:
          containers:
          - image: $image
            imagePullPolicy: IfNotPresent
            name: pytorch
          - image: $image
            imagePullPolicy: IfNotPresent
            name: pytorch
```
It needed a different `name`
